all:
  children:

    proxmox_nodes:
      hosts:
        hpmini:
          ansible_host: 192.168.0.2
        hpmini1:
          ansible_host: 192.168.0.3
        hpmini2:
          ansible_host: 192.168.0.5

    k8s:
      children:

        control_plane:
          hosts:
            k8s01m01:
              ansible_host: 192.168.15.16
              vmid: 3500
              pve_node: hpmini

            k8s01m02:
              ansible_host: 192.168.15.11
              vmid: 3501
              pve_node: hpmini1

            k8s01m03:
              ansible_host: 192.168.15.12
              vmid: 3502
              pve_node: hpmini2

        workers:
          hosts:
            k8s01w01:
              ansible_host: 192.168.15.13
              vmid: 3503
              pve_node: hpmini

            k8s01w02:
              ansible_host: 192.168.15.14
              vmid: 3504
              pve_node: hpmini1

            k8s01w03:
              ansible_host: 192.168.15.15
              vmid: 3505
              pve_node: hpmini2



